// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAGNu15tMFMFO2EXrGWLc5SG25iCkbY5I',
    appId: '1:46885657826:web:b1e58f203120fc663a92bb',
    messagingSenderId: '46885657826',
    projectId: 'appflutter-5c671',
    authDomain: 'appflutter-5c671.firebaseapp.com',
    storageBucket: 'appflutter-5c671.appspot.com',
    measurementId: 'G-ZXV6Y4Z31B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaaCrz9-JNrXBpEV6617gXCU8Kn7LxGA',
    appId: '1:46885657826:android:8057cdaf682018273a92bb',
    messagingSenderId: '46885657826',
    projectId: 'appflutter-5c671',
    storageBucket: 'appflutter-5c671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIrwnDOxpxB61jw77LJtm_-GWwiHDxe28',
    appId: '1:46885657826:ios:d3c21e3aea2fb1bc3a92bb',
    messagingSenderId: '46885657826',
    projectId: 'appflutter-5c671',
    storageBucket: 'appflutter-5c671.appspot.com',
    iosClientId: '46885657826-il7p8nsnoddd8l0dib97cbdefqr66mvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIrwnDOxpxB61jw77LJtm_-GWwiHDxe28',
    appId: '1:46885657826:ios:7c8c8d611d066a6f3a92bb',
    messagingSenderId: '46885657826',
    projectId: 'appflutter-5c671',
    storageBucket: 'appflutter-5c671.appspot.com',
    iosClientId: '46885657826-73r4vb2vush1a4su0vrlj0i94et4hs9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
